config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :dogs, only: %i[index show new create] do
    resources :bookings, only: %i[new create confirmation]
  end
  resources :bookings, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dog
  validates :start_on, :end_on, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def age
    (Date.today - born_on).to_i / 365
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new
  end

  def create
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new(booking_params)
    @booking.dog = @dog
    @booking.user = current_user
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_on, :end_on)
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @dogs = Dog.all
    @markers = @dogs.geocoded.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude
      }
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    @dog.address = current_user.address

    if @dog.save # t f
      redirect_to dog_path(@dog)
    else
      render :new
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :breed, :born_on, :sex, :size, :neutered, :bio, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Complete your booking for <%= @dog.name %> dog</h3>
        <%= simple_form_for [@dog, @booking] do |f| %>
          <%= f.input :start_on, html5: true, required: true, placeholder: 'choose when you want your time to start' %>
          <%= f.input :end_on, html5: true, required: true, placeholder: "choose when you want your time to end" %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-3" style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
  <h1>Thank You!</h1>
  <p>Booking confirmation for <%= @booking.dog.name %> from <strong><%= @booking.start_on %></strong> until <strong><%= @booking.end_on %></strong></p>
</div>

app/views/dogs/index.html.erb
<div class="container-fluid pe-0">
  <div class="row me-0">
    <div class="col-lg-8">
      <h1 class="mt-3">Take a look at our friends!</h1>
      <div class="row">
        <% @dogs.each do |dog| %>
          <div class="col-xs-12 col-sm-6 col-lg-4 col-sm-offset-1">
            <div class="card mb-3">
              <%= cl_image_tag dog.photo.key, class: "img-fluid", :width=>500, :height=>500, :gravity=>"face", :crop=>"thumb" %>
              <div class= "card-body">
                <h4 class="mb-0">
                  <%= dog.name %>
                </h4>
                <p class="fs-6 text-muted"><%= dog.breed %></p>
                <div class="text-end">
                  <%= link_to "View dog", dog_path(dog.id), class: 'btn btn-primary stretched-link btn-sm' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <div style="width: 100%; height: 400px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/dogs/new.html.erb
<div class="container">
  <div class="row justify-content-center py-5">
    <div class="col-lg-4">
      <h1>Listing a Dog</h1>
      <%= simple_form_for @dog do |f| %>
        <%= f.input :name %>
        <%= f.input :breed %>
        <%= f.input :born_on, html5: true %>
        <%= f.input :sex, collection: %w[male female], as: :radio_buttons %>
        <%= f.input :size, collection: %w[small medium large giant], as: :radio_buttons %>
        <%= f.input :neutered %>
        <%= f.input :photo, as: :file %>
        <%= f.input :address %>
        <%= f.button :submit, "Submit", class: "btn btn-primary w-100 rounded-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/dogs/show.html.erb
<div class="container my-5">
  <h1><%= @dog.name%></h1>
  <p><%= @dog.address%></p>
  <%= cl_image_tag @dog.photo.key, class: "img-fluid mb-3", height: 600, width: 1200, crop: :fill %>


  <div class="bg-light p-3">
    <p class="border-start fst-italic ps-3">
      Hi, I'm <mark><%= @dog.name%></mark>! Nice to meet you! I'm a <mark><%= @dog.age %> year old</mark>, <mark><%= @dog.size%> <%= @dog.breed%></mark>.
      I'm a <mark><%= @dog.sex%></mark> and I'm <mark><%= @dog.neutered? ? "neutured" : "not neutered" %></mark>. I'm paws-itive that we'll be just mutts about each other!
    </p>
    <p><%= @dog.bio%></p>

    <%= link_to "Start Booking", new_dog_booking_path(@dog.id), class: 'btn btn-primary' %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Share A Dog</title>
    <link rel="preconnect" href="http://www.shareadog.net/">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer" %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js' defer></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="d-flex" style="background: #E8AD22; height: calc(90vh - 66px); padding: 70px;">
  <div class="overflow-hidden w-100 max-height: 90vh;">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
    <lottie-player src="https://assets10.lottiefiles.com/packages/lf20_lc6foY.json"  background="#E7AC22"  speed="1.5"  class="w-100 overflow-hidden"  loop  autoplay></lottie-player>
  </div>

  <div class="d-flex align-items-center justify-content-center flex-column w-100">
    <p style="text-align: center; margin-right: 10px;">We're here to help you find the perfect companion for a day</p>
    <%= link_to "Find your new best friend!", dogs_path, class: "btn btn-primary btn-lg mb-2" %>
    <%= link_to "Share your dog", new_dog_path, class: "btn btn-secondary btn-sm" %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static0.thethingsimages.com/wordpress/wp-content/uploads/2018/08/Man-Giving-His-Dog-A-High-Five.jpg);">
  <div class="container">
    <p>share your day, share your love, share your dog</p>
    <%= link_to "Find your new best friend!", dogs_path, class: "btn btn-primary" %>
    <%= link_to "List your dog", new_dog_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="fixed-bottom bg-light text-center text-dark">
  <p class="mt-3">&copy; 2023 ShareADog</p>
</footer>